### PR TITLE
Implemented generic Iso, in the vein of Control.Lens.Wrapped

### PR DESCRIPTION
**Pull request by LightAndLight**
I'd like to float the the idea of generic `Iso`s, providing the same functionality as `Control.Lens.Wrapped`.

If you think this is useful then I'll do the work to get the documentation/module structure/code style/tests up to scratch.

### CODE REVIEW

**Comment by kcsongor** [comment]
The idea of providing `Iso`s sounds good! We could generalise this to types that have the same structure, so we could derive isomorphisms between
```haskell
data E1 a b = L1 a | R1 b
```
and
```haskell
data E2 a b = L2 a | R2 b
```
etc.
Or maybe the more restricted `Wrapped` is useful in its own right?

**Comment by LightAndLight** [comment]
I like that idea :) I'll have a bit of a play over the next couple of days

**Comment by LightAndLight** [comment]
It took me a while to get around to it, but I've implemented this here: https://github.com/LightAndLight/generic-lens/blob/structural-equality/src/Data/Generics/Iso.hs

One thing that I don't like about this is that declaration order is significant. So `data Maybe' a = Just a | Nothing` is not convertible to `Maybe a`, because `Maybe` has `Nothing` as the its first constructor. That's  kinda yucky.

I think my ideal implementation would try to derive a unique iso, and fail if there are zero possible isos, or more than one possible iso. This would mean that `Bool` could not have an iso derived for it because there are two valid `Iso' Bool Bool`.

At this stage, Wrapped seems to be the only "definitely good and useful" thing here. What do you think?

**Comment by kcsongor** [comment]
I see, this all makes sense. Thanks for the exploration! I agree that ideally the ordering of constructors shouldn't matter, so let's think about that a bit more, as it's certainly exciting.

The class you've provided in this PR is useful in its own right (in that it's not really a special case of the structural one, but a slightly different direction, now that I thought about it more), and I'm happy to merge it in.

Two minor things:
1, I think we should change the name from `Is` to something like `Wrapped` or `Newtype`, as the name `Is` is maybe too general. Mainly, I would expect a class called `Is` to have the fundeps going both ways.
2, I see you used the van Laarhoven representation in your implementation. Is there any particular reason for this? In the rest of the library, we use a profunctor representation internally, and transform to the van Laarhoven for the API (with the plan being to also provide profunctor optics in the public API). Would you mind tweaking the code to be in that style instead?

Thanks for putting the time into this, looks great!

**Comment by LightAndLight** [comment]
Yeah `Wrapped` or `Newtype` is fine, shall we flip a coin?

And I only used the van laarhoven optic because that was the first one I reached for. It'll be no trouble to switch to profunctors.

**Comment by LightAndLight** [comment]
Cool. `Control.Lens.Wrapped` is the reason I wrote this :)

**Comment by LightAndLight** [comment]
Have I used profunctor and van laarhoven lenses in the correct places now?

**Comment by kcsongor** [comment]
Yes, sorry, I forgot about this! Thanks

**Pull request merged**
