### PR TITLE
[WIP] Generic optics

### PR DESCRIPTION
**Pull request by kcsongor**
Decided to do a more thorough reorganisation.
Most things work, but inspection tests fail at the moment. I haven't looked into them yet.

/cc @phadej

### CODE REVIEW

**Comment by kcsongor** [comment]
Inspection-tests are now looking quite good.

**Comment by kcsongor** [comment]
Inspection tests pass on 8.6 and 8.8, which is great news, because they were failing before. But now I need to figure out what went wrong with 8.4.

**Comment by kcsongor** [comment]
@phadej all the inspection tests now pass on 8.4-8.8, and 8.10 fails to build because of dependency issues, so I will need to look into that more. I got tempted to drop support for <8.4, because this allowed removing many of the hacks (including all of the CPP).

The only missing thing now is optimising the traversals in `generic-optics`, then fixing up haddocks. Can you think of anything else to be done before I make a release?

**Comment by phadej** [comment]
It would be nice to write down the (all / most of) hacks you have been able to drop, that would justify dropping of support for <8.4 in the changelog well. (as well as generally good reference).

For testing GHC-8.10 (or bleeding edge in general), you could add to the `cabal.project`:

```cabal
-- For the bleeding edge:
--
repository head.hackage
   url: https://ghc.gitlab.haskell.org/head.hackage/
   secure: True
   root-keys: 7541f32a4ccca4f97aea3b22f5e593ba2c0267546016b992dfadcd2fe944e55d
              26021a13b401500c8eb2761ca95c61f2d625bfef951b939a8124ed12ecf07329
              f76d08be13e9a61a377a85e2fb63f4c5435d40f8feb3e12eb05905edb8cdea89
   key-threshold: 3

allow-newer: *:base
allow-newer: *:Cabal
allow-newer: *:ghc
allow-newer: *:ghc-prim
allow-newer: *:template-haskell
```

and then `cabal v2-update head.hackage` (in the project directory). You might need to `rm -rf ~/.cabal/packages/head.hackage` first if you have older ones, due to bug in `cabal-install`. (Use `head.hackage` only with GHC-8.10).

I did `haskell-ci regenerate` (using recent `haskell-ci`) and pushed the commit; that should fix Travis.

**Comment by phadej** [comment]
And about what to do before the release, I cannot tell, you know better :)

**Comment by kcsongor** [comment]
> It would be nice to write down the (all / most of) hacks you have been able to drop, that would justify dropping of support for <8.4 in the changelog well. (as well as generally good reference).

Good idea! Where should a writeup like this live? Maybe I'll put them in a blog post for future reference...

**Comment by phadej** [comment]
@kcsongor I was to propose it might make a blog post.

**Comment by phadej** [comment]
Also, CI is green and running doctest.

**Comment by kcsongor** [comment]
Oh, it looks like all the tests passed on 8.10.1 too, including the inspection-tests. Beautiful!

**Comment by kcsongor** [comment]
Done!

**Comment by phadej** [comment]
congrats on the rewrite! I trust you that it works :)

**Comment by kcsongor** [comment]
Thanks, I'm reasonably confident that it does :) now I'm writing the changelog then it's all done.

**Pull request merged**
