### PR TITLE
Identity lens for HasType

### LINKED ISSUE #71: Identity lenses using `typed`
This code fails:

```haskell
{-# LANGUAGE FlexibleContexts, DeriveGeneric, TypeApplications #-}

module GenLens where

import GHC.Generics
import Control.Lens
import Data.Generics.Product

data Foobar = Foobar Int Char String
    deriving Generic

foo :: HasType Foobar ctx => ctx -> Char
foo ctx = case view (typed @Foobar) ctx of
    Foobar _ c _ -> c

bar :: IO ()
bar = do
    print (foo (Foobar 3 'a' "Hello"))
```

with this error message:

```
/home/matt/Projects/playground/src/GenLens.hs:18:12: error:
    • The type Foobar does not contain a value of type Foobar
    • In the first argument of ‘print’, namely
        ‘(foo (Foobar 3 'a' "Hello"))’
      In a stmt of a 'do' block: print (foo (Foobar 3 'a' "Hello"))
      In the expression: do print (foo (Foobar 3 'a' "Hello"))
   |
18 |     print (foo (Foobar 3 'a' "Hello"))
   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
```

I would expect that it would work out to the identity lens: `id :: Lens' a a`

### PR DESCRIPTION
**Pull request by parsonsmatt**
This passes all the tests, but it causes inspection testing to fail :\

Fixes #71

### CODE REVIEW

**Comment by parsonsmatt** [comment]
So defining `typed = id` causes inspection testing to fail, but defining `getTyped` and `setTyped` causes it to succeed! Weird.

**Comment by kcsongor** [comment]
Sorry for the late response! I've been thinking about this, and I think I'm convinced that doing this is a good idea. It's a breaking change, but it's quite unlikely that many people rely on the current behaviour, as it's just not that useful...

**Comment by parsonsmatt** [comment]
:heart: thanks :smile:

**Comment by kcsongor** [comment]
Thanks a lot for this!

**Pull request merged**
