### PR TITLE
Parameterize definition of interesting types for `types`

### PR DESCRIPTION
**Pull request by Lysxia**
Follow up on the discussion at #73 about making `types` more scaleable.

- Introduce redefinable `Children` type family with which `Interesting` is defined (a function mapping every type to the set of types of its fields);
- `types` keeps the default definition for compatibility and convenience;
- `typesUsing` is the generalized version.

Also anticipating on potential `HasTypes` instances for containers (`Map`, `Vector`), I refactored the type comparison previously in the `Rec0` case into a separate class `HasTypes0`. Otherwise we would have to duplicate that logic:

```haskell
instance {-# OVERLAPPING #-} HasTypes (Vector a) a where
  types_ = traverse

instance HasTypes a b => HasTypes (Vector a) b where
  types_ = traverse . types_
```

This also makes the idea in #71, of having the `HasTypes a a` instance produce the identity lens, quite feasible.

### CODE REVIEW

**Comment by Lysxia** [comment]
The remaining errors don't seem to be caused by this PR (doctest can't find modules)

**Comment by kcsongor** [comment]
Thanks, this is a really neat solution!

I'm trying to understand the hierarchy, we have `HasTypes`, `HasTypesUsing`, `HasTypes0`, `HasTypes1` and `HasTypes'`.

`HasTypes` is a synonym for `HasTypesUsing ChDefault`. `HasTypesUsing` then delegates to `HasTypes1` which does the node skipping optimisation. When the node is not skipped, `HasTypes'` is called, which in turn calls the generic derivation. It seems to me that this is the "configuration point" where users can inject their own traversals.

For example, if we have `Bar` with no `Generic` instance, but we still want to traverse its content, we could say

```haskell
data Bar = Bar Bool
  deriving (Show)

data Foo = Foo (Maybe Int) [Int] Bar
  deriving (Show, Generic)

data Custom
type instance Children Custom a = ChildrenCustom a

type family ChildrenCustom (a :: Type) where
  ChildrenCustom Bar = '[Bool]
  ChildrenCustom a   = Children ChDefault a

instance HasTypes' Custom Bar Bool where
  types' f (Bar x) = fmap Bar (f x)
```

Then finally, in the recursive case of `GHasTypes`, `HasTypes0` first checks if the target matches the child, and keeps going if it doesn't.
Is this an accurate description of what's happening, or did I miss something?

If I understand correctly, having a `HasTypes a a` instance would help with the `Vector` example, because we would only have to define the

```haskell
instance HasTypes a b => HasTypes (Vector a) b where
  types_ = traverse . types_
```

instance (and not the `HasTypes (Vector a) a` one), but what's not clear to me is how `HasTypes0` helps with this (i.e. moving this check out into a new class from the `Rec0` case)

**Comment by kcsongor** [comment]
Looks like most of this work will be directly applicable to https://github.com/kcsongor/generic-lens/issues/75 too

**Comment by Lysxia** [comment]
That description looks accurate to me. I agree `HasTypes'` is where you would want to add custom instances.

An instance `HasTypes a a`  currently (this PR doesn't change that) looks for `a`'s nested in `a`, rather than returning the current `a` directly. In particular, when `a = Int`, `HasTypes Int Int` gives an empty traversal. Now if you naively write an instance `HasTypes s a => HasTypes (Vector s) a`, then `HasTypes (Vector Int) Int` will be an empty traversal.

Factoring out the equality check in its own class `HasTypes0`, we can instead write `HasTypes0 s a => HasTypes (Vector s) a`, which will do the expected thing for `HasTypes (Vector Int) Int`, namely a traversal of every element of the vector.

Another solution is to have the check happen by default from the start in `HasTypes` (or `HasTypesUsing` after this PR), so that `HasTypes a a` always gives the singleton traversal `id`. This might make it more difficult to get handwritten instances wrong for container types.

**Comment by kcsongor** [comment]
Right, what confused me a little was that `HasTypes0` is not exported from the module, but for this to work, it really should be.
All said, I think I would be inclined to have the equivalent of https://github.com/kcsongor/generic-lens/pull/72 for the traversal too, as that would make things quite a bit simpler like you said.

An unfortunate consequence of the separate `HasTypes'` class seems to be that the custom instance only works when the type in question appears as a child, but not at the top-level (for that we would need an additional `HasTypesUsing` instance).

But, if `HasTypes0` and `HasTypesUsing` were to be merged, then `HasTypeUsing` could be the place to define the custom instances. As far as I can tell, the only consequence of that would be that the optimisation would not happen in these cases, but that might be acceptable, given the relative rarity of these.

**Comment by kcsongor** [comment]
Thanks @Lysxia, I did a bit of refactoring and merged this patch.

**Pull request merged**
