### PR TITLE
uncomment Data.Generics.Labels

### PR DESCRIPTION
**Pull request by tonyday567**
ready to go?

### CODE REVIEW

**Comment by kcsongor** [comment]
I've been thinking about putting this in, but it seems a little dangerous. It's an orphan instance, and importing it in a library could transitively break programs that have another orphan defined (AFAIK, some extensible record libraries do this).

Even if it was included, I think the fact that it's an orphan would make this a breaking change. What do you think?

**Comment by tonyday567** [comment]
Yep, agree it's a breaking change.

Personally, I like the api (see https://github.com/tonyday567/chart-unit/blob/cleanup/examples/sourceExamples.hs#L33 for instance - very easy on the eye) and the tradeoff is well worth it.  I think others would agree, and so Data.Generics.Labels would be great to have in stack somewhere.  We could go with a separate library eg https://github.com/duog/generic-lens-labels but it would closely follow whatever developments happen in generic-lens so there are obvious synergies including the module here.

Downside is that some do get scared off by the whole orphan instance thing, and you might have to watch out for library reputation risk, where peeps assume the orphan instance pollutes the whole library.

Do you know which extensible record libraries are the ones to worry about?  I'm happy to do some research and see how hard it is to break stuff.

**Comment by tonyday567** [comment]
Reading through the [original proposal](https://github.com/ghc-proposals/ghc-proposals/pull/6), the orphan instance was going to be added to GHC itself, but the tribe got hung up on whether the instance was going to be based on lens or selectors.

So supplying an orphan instance is the expectation of the language pragma rather than any sort of poor design.  If the proposal ever gets completed, I image Data.Generics.Labels would be deprecated for a GHC version of the same thing.

In summary, I'd say supplying an orphan instance is expected, and contributes to the whole experiment as GHC progresses.

Along the way, some instances that may be of interest.  Looking at record libraries:

- [bookkeeper](https://github.com/turingjump/bookkeeper/blob/f50a2ea01abf02a3a03c9f38ec3ca8635780d8fb/src/Bookkeeper/Lens.hs) supplies an orphan instance of IsLabel for (->) that does indeed smash into the generic-lens version.

- [extensible](https://github.com/fumieval/extensible/blob/6746278d192ae95b436b6a8cdbecdc2c76075987/src/Data/Extensible/Label.hs) looks kind of like it has an orphan IsLabel instance for (->) but didn't compile with stack nightly so I didn't test.

- [rawr](https://github.com/PkmX/rawr/blob/master/src/Data/Rawr.hs#L689) looks like a direct clash but it isn't in stack so I didn't confirm this.

Other record libraries (vinyl, records) looked fine.

A few notable instances:

- [dbrecord](https://github.com/byteally/dbrecord/blob/315949f243947bf3e38b5835d6ac3bd1872f8c10/src/DBRecord/Internal/Types.hs#L17) looks like a newtype wrapped (->) orphan

- [proto-lens](https://github.com/google/proto-lens/blob/b342f24e6366474434a48f9510ea42f1bc46d64f/lens-labels/src/Lens/Labels/Unwrapped.hs) another approach of a newtype wrapped IsLabel instance.

**Comment by kcsongor** [comment]
Thanks for doing the research, this is very useful!

Those instances would indeed clash with this one, and I still think that hijacking an instance for something as ubiquitous as `->` is a dangerous idea. There was some previous discussion here: https://github.com/kcsongor/generic-lens/issues/11. (Out of which the generic-lens-labels library was born).

I do agree that the API is very compelling, but even after reading the proposal, it seems to me that this is not a good idea.
As an alternative solution, we could have a newtype wrapper around the lens with a short selector function, something like ` _f #foo . _f #bar . _f #baz`.

What do you think about this?

**Comment by tonyday567** [comment]
I don't mind `field @"foo" . field @"bar" . field @"baz"` etc if it's just a few combinators in amongst other stuff.  Personally, when the code gets busy, I think it comes down to reducing the amount of punctuation which I'll define as non-alphanumeric characters.  And, for this case, an unwrapping _f prefix doesn't get very far compared with the combat readiness of `#foo . #bar . #baz`.

It's a reasonable decision to not include the instance, and it does tend to muddy the library some.  Given this decision, I'd say that a separate library for Data.Generics.Labels is ideal.

**Comment by 3noch** [comment]
At the very least you'd want to change the module name to something scary like `Data.Generics.Labels.Orphans`.

**Comment by 3noch** [comment]
Another option would be to hide the module behind a cabal flag. This way libraries would be much less likely to use it. But that might be a bit much.

**Comment by 3noch** [comment]
As a side note, I wish it were possible to make the instance only apply to fields that start with some prefix (say `_`) similar to how `makeLenses` works. This would also make the instance less invasive.

**Comment by kcsongor** [comment]
@tonyday567 Yes, that's a good point, the labels are definitely more appealing. Perhaps the right solution is to have it in a separate library, I wouldn't mind that. It's a more explicit opt-in, if people want to use it that way. If this works, then I would be happy to maintain @duog's library on stackage, unless he wishes to do so himself.
(https://github.com/duog/generic-lens-labels/issues/5)
Notably, the version bounds need updating every now and then.

@3noch I agree, it would be great to have some a more fine-grained control over these instances, but unfortunately I don't think it's possible.
Even requiring some more constraints on the instance, ultimately, the instance head is still defined for some variation of `->`, which is what gets picked up by instance resolution first.

**Comment by duog** [comment]
@kcsongor I intend to publish to generic-lens-labels to hackage and stackage today. I will give you, @3noch and @tonyday567 commit bits.

I see that your instance head is:
```haskell
instance (HasField field s t a b, Functor f, sft ~ (s -> f t)) => IsLabel field ((a -> f b) -> sft)
```
whereas mine is (or would be with type-changing lenses):
```haskell
instance (HasField field s t a b, Functor f, lens ~ ((a -> f b) -> s -> f t)) =>
IsLabel x lens
```
.  I assume your version has better instance resolution in some cases, are you able to provide any examples?

**Comment by kcsongor** [comment]
@duog 

Ideally, I wanted the instance to look like
```haskell
instance (HasField field s t a b, Functor f) => IsLabel field ((a -> f b) -> s -> f t) where
```
but this version (as you probably found too) has very bad inference.

Basically I wanted to move as much of the type into the head as I could, so as to "steal" less instances, and maybe allow for some other ones to coexist. In particular, libraries that play nicely and define `IsLabel` for their newtypes wouldn't clash with our orphan. Sadly, this doesn't apply to the field selector instances of extensible records libraries, as @tonyday567's research shows too, since those define the instances for some `a -> b`, which again, does overlap with our instance. Perhaps playing with some per-instance overlap pragmas could improve this? I haven't thought too much about that.

In terms of instance resolution, I think yours is better if one wants to use labels exclusively for these lenses. An obvious argument in favour of your instance would be ghci sessions:

```
>>> :t #foo
#foo :: GHC.OverloadedLabels.IsLabel "foo" t => t
```
vs
```
>>> :t #foo
#foo :: (Functor f, HasField "foo" s t a b) => (a -> f b) -> s -> f t

```

So this is something else to think about...

**Comment by kcsongor** [comment]
I'm closing this, as I think we have agreed to a sensible solution. Thanks!

**Pull request closed without merging**
