### PR TITLE
Add GHC-8.6 to travis

### PR DESCRIPTION
**Pull request by phadej**
`inspection-testing` can GHC-8.6 now, so...

```haskell
### Failure in: 0                          
test/Util.hs:10
test/Spec.hs:219:7: fieldALensManual === fieldALensName failed:
    LHS:
        fieldALensManual
        fieldALensManual
          = \ @ f $dFunctor_amTo f ds_dqAY ->
              case ds_dqAY of { MkRecord a b ->
              fmap $dFunctor_amTo (\ a' -> MkRecord a' b) (f a)
              }
        
    RHS:
        $s$fHasTypeas_$ctyped
        $s$fHasTypeas_$ctyped
          = \ @ f w3 w4 w5 ->
              case w3 of { C:Functor ww1 ww2 ->
              case w5 of { MkRecord g1 g2 ->
              ww1 (\ x1 -> MkRecord x1 g2) (w4 g1)
              }
              }
        
        fieldALensName
        fieldALensName = $s$fHasTypeas_$ctyped
        
### Failure in: 1                          
test/Util.hs:10
test/Spec.hs:220:7: fieldALensManual === fieldALensType failed:
    LHS:
        fieldALensManual
        fieldALensManual
          = \ @ f $dFunctor_amTo f ds_dqAY ->
              case ds_dqAY of { MkRecord a b ->
              fmap $dFunctor_amTo (\ a' -> MkRecord a' b) (f a)
              }
        
    RHS:
        $s$fHasTypeas_$ctyped
        $s$fHasTypeas_$ctyped
          = \ @ f w3 w4 w5 ->
              case w3 of { C:Functor ww1 ww2 ->
              case w5 of { MkRecord g1 g2 ->
              ww1 (\ x1 -> MkRecord x1 g2) (w4 g1)
              }
              }
        
        fieldALensType
        fieldALensType = $s$fHasTypeas_$ctyped
        
### Failure in: 4                          
test/Util.hs:10
test/Spec.hs:223:7: typeChangingManual === typeChangingGeneric failed:
    LHS:
        typeChangingManual
        typeChangingManual
          = \ @ a @ b @ f $dFunctor_amUw f ds_dqBr ->
              case ds_dqBr of { MkRecord3 a b ->
              fmap $dFunctor_amUw (\ a' -> MkRecord3 a' b) (f a)
              }
        
    RHS:
        typeChangingGeneric
        typeChangingGeneric
          = \ @ a @ b @ f $dFunctor_amLu w11 w12 ->
              case $dFunctor_amLu of { C:Functor ww1 ww2 ->
              case w12 of { MkRecord3 g1 g2 ->
              ww1 (\ x1 -> MkRecord3 x1 g2) (w11 g1)
              }
              }
```

### CODE REVIEW

**Comment by phadej** [comment]
All three errors seems to be so generic case matches on `Functor` dictionary record, where manual uses selector. I guess these are equivalent, but I don't know how to tell `inspection-testing` that...

**Comment by kcsongor** [comment]
Hm, this looks interesting, any idea why this might be happening?

/cc @mpickering

**Comment by phadej** [comment]
@kcsongor I have to admit, `generic-lens` is great piece of work.

I don't know why exactly (I have no idea what changes in GHC), but my small change seems to work.

My guiding rule here is *Rank1Type is simpler than Rank2Type*.

**Comment by phadej** [comment]
Screw that, travis disagrees :/

**Comment by phadej** [comment]
With small change

```diff
diff --git a/src/Data/Generics/Internal/VL/Lens.hs b/src/Data/Generics/Internal/VL/Lens.hs
index 35e7064..448a530 100644
--- a/src/Data/Generics/Internal/VL/Lens.hs
+++ b/src/Data/Generics/Internal/VL/Lens.hs
@@ -54,7 +54,7 @@ lens2lensvl :: Functor f => ALens a b s t -> LensLike f s t a b
 lens2lensvl (ALens _get _set) =
   \f x ->
     case _get x of
-      (c, a) -> _set . (c, ) <$> f a
+      (c, a) -> _set . (c, ) `fmap'` f a
 {-# INLINE lens2lensvl #-}
 
 ravel :: (ALens a b a b -> ALens a b s t)
@@ -66,3 +66,7 @@ lens :: (s -> a) -> ((s, b) -> t) -> Lens s t a b
 lens get _set = \f x -> curry _set x <$> f (get x)
 {-# INLINE[0] lens #-}
 
+infixl 4 `fmap'`
+fmap' :: Functor f => (a -> b) -> f a -> f b
+fmap' = fmap
+{-# NOINLINE fmap' #-}
```

Everything obviously doesn't work, but maybe it's clearer that GHC-8.6 for some reason (maybe commit mentioned above) matches on `Functor` dictionary in wrapper/worker transform. In GHC-8.6 version the dictionary is matched on, and then again assembled so it can be given to `fmap'`. 

I don't see a problem with new Core, so maybe we just have to teach `inspection-testing` a new trick (which is quite fancy trick :/)

---

### GHC-8.6

```haskell
    LHS:
        fieldALensManual
        fieldALensManual
          = \ @ f $dFunctor_amUY f ds_dqCy ->
              case ds_dqCy of { MkRecord a b ->
              fmap $dFunctor_amUY (\ a' -> MkRecord a' b) (f a)
              }
        
    RHS:
        $wfieldALensName
        $wfieldALensName
          = \ @ f ww_svSA w_svSw ww_svSF ww_svSG ->
              fmap'
                (C:Functor ww_svSA $fHasField'fieldsa1)
                (\ x1 -> MkRecord x1 ww_svSG)
                (w_svSw ww_svSF)
        
        fieldALensName
        fieldALensName
          = \ @ f w_svSv w_svSw w_svSx ->
              case w_svSv of { C:Functor ww_svSA ww_svSB ->
              case w_svSx of { MkRecord ww_svSF ww_svSG ->
              $wfieldALensName ww_svSA w_svSw ww_svSF ww_svSG
              }
              }
```

### GHC-8.4.3

```haskell
    LHS:
        fieldALensManual
        fieldALensManual
          = \ @ f $dFunctor_as1d f ds_dvfW ->
              case ds_dvfW of { MkRecord a b ->
              fmap $dFunctor_as1d (\ a' -> MkRecord a' b) (f a)
              }
        
    RHS:
        fieldALensName
        fieldALensName
          = \ @ f $dFunctor_arUl w11 w12 ->
              case w12 of { MkRecord g1 g2 ->
              fmap' $dFunctor_arUl (\ x1 -> MkRecord x1 g2) (w11 g1)
              }
```

**Comment by kcsongor** [comment]
Should we just try and change `inspection-testing` to be more lenient? I'm not sure how to proceed from here.

**Comment by phadej** [comment]
I forgot about this during HaskellX, and didn't ask neither Simon nor Joachim about this.

Let's try to make a more minimal example where (`Functor`) dictionary is scrutinised in worker/wrapper. It will help as discussion opener.

**Comment by mpickering** [comment]
I asked Simon about this at ICFP and he said that it was probably because fieldALensManual is too small to consider to WW. I should be resonsible for investigating this precisely.

**Comment by phadej** [comment]
Outdated.

**Pull request closed without merging**
