### PR TITLE
Expose OnlyOne

### LINKED ISSUE #53: Expose a convenient constraint for "lacking" a type
I've got a gist for typed exception handling using generic-lens and classy prisms: https://gist.github.com/parsonsmatt/880fbf79eaad6ed863786c6c02f8ddc9

The important bits:

```haskell
data FooErr = FooErr Int
    deriving (Show, Generic)

data BarErr = BarErr String
    deriving (Generic, Show)

foo :: AsType FooErr e => Either e Int
foo = Left (review (_Typed @FooErr) (FooErr 3))

bar :: AsType BarErr e => Either e Int
bar = Left (review (_Typed @BarErr) (BarErr "hello"))

foobar :: (AsType BarErr e, AsType FooErr e) => Either e Int
foobar = bar *> foo *> bar

plucked :: _ => Either (Either FooErr e) Int
plucked = foobar
```

So the `plucked` function has a type wildcard, for two reasons: a) the type families are not exposed at all, and b) the inferred constraint is kind of huge. I would like to be able to write something like:

```
plucked :: (AsType BarErr e, Lacking FooErr e) => Either (Either FooErr e) Int
```

I *think* that's what the inferred constraints roughly mean.

### PR DESCRIPTION
**Pull request by parsonsmatt**
This PR makes a type alias for the constraint you need for the `AsType` instances. This allows me to write:

```haskell
foobar :: (AsType BarErr e, AsType FooErr e) => Either e Int
foobar = bar *> foo *> bar

plucked
    ::
    ( AsType BarErr (Either FooErr e)
    , OnlyOne FooErr (Either FooErr e)
    ) => Either (Either FooErr e) Int
plucked = foobar

-- or,

plucked 
    :: (AsType BarErr err, OnlyOne FooErr err, err ~ Either FooErr e)
    => Either err Int
```

which deeply pleases me

Resolves #53

### CODE REVIEW

**Comment by kcsongor** [comment]
I'll have to admit I've not tried this yet, but could you explain what the motivation for `OnlyOne` is? My understanding is that `OnlyOne FooErr e` ensures that `e` contains only one constructor with `FooErr` in it, but `AsType FooErr e` already says this implicitly, at least when it's instantiated through generics:

```haskell
plucked
    ::
    ( AsType BarErr (Either FooErr e)
    , AsType FooErr (Either FooErr e)
    ) => Either (Either FooErr e) Int
plucked = foobar
```

My only qualm is that in its current form, `OnlyOne` incurs a `Generic` constraint, but `AsType` tries to be abstract, in that you can provide your own (overlapping) instance if need be. Perhaps making `OnlyOne` also a type class with a "default" instance in terms of `Generic` and `GAsType` would mirror that more closely.

----

After staring at #53 a bit longer, it seems like the constraint is just the `AsType` one being expanded. It would be great if we could somehow stop this expansion from happening in the error message. Do you have any ideas how that would be achievable?

**Comment by parsonsmatt** [comment]
You're exactly right. That works just fine :sweat_smile: 

You can stop expansions of things by using a type family instead of a type alias or direct constraints, I'm pretty sure -- a one-case closed type family is basically a type alias, but GHC will get "stuck" on it if it can't solve it, rather than dumping what it is. But this does make error messages more opaque.

**Comment by kcsongor** [comment]
Making error messages more opaque would be fine so long as it's only implementation details that get hidden (such as the one in #53). Either way, what should happen with this?
I have been using `AsType` as a way of doing ad-hoc error handling, but the technique is not written down anywhere, so maybe something like a tutorial is what we need?

**Comment by parsonsmatt** [comment]
I'm in the process of writing up a library/tutorial that does error handling with `AsType`, but you might beat me to it if you have more experience :)

**Comment by kcsongor** [comment]
Sadly I don't have much time to write about this in the next couple of weeks, but here's how I use it:

```haskell
-- | MonadError' is a generalised version of MonadError
--  We have some large error type 'e', and we can inject the constituent parts 'err'
class (Monad m, MonadError e m)
  => MonadError' err e m | m -> e where
  throwError' :: err -> m a
  catchError' :: m a -> (err -> m a) -> m a

-- We can either throw the large error type as it is
instance (Monad m, MonadError e m) => MonadError' e e m where
  throwError' = throwError
  catchError' = catchError

-- ...or inject via AsType
instance {-# OVERLAPPABLE #-}
  ( Monad m
  , MonadError e m
  , AsType err e
  ) => MonadError' err e m where
  throwError' e = throwError (injectTyped e)
  catchError' ma h = catchError ma $ \e ->
    case projectTyped e of
      Just e  -> h e
      Nothing -> ma

```

Then for some sum error type

```haskell
data AppError
  = AppNetworkError NetworkError
  | AppAuthError AuthError

login ::
  ( MonadError' NetworkError e m
  , MonadError' AuthError e m
  ) => String -> String -> m String
login ip username = do
  when (not (validIP ip)) $
    throwError' (NetworkError "Invalid IP")
  when (not (validUser username)) $
    throwError' (AuthError "Invalid user")
  return username
```

And we can also selectively handle specific errors, without having to jump through the hoops with `SomeException` that classy prisms suffers from:

```haskell
loginOrGuest ::
  ( MonadError' NetworkError e m
  , MonadError' AuthError e m
  ) => String -> String -> m String
loginOrGuest ip username
  = catchError' @AuthError (login ip username) (const (login ip "guest"))
```

**Pull request closed without merging**
