### PR TITLE
Add instance AsType a a

### LINKED ISSUE #146: Reflexive instances for AsType?
There appears to be reflexive instances for AsSubtype and HasType, but not for AsType.

Consider:

```haskell
data SomethingError = OhNo
  deriving (Generic)

doSomething :: (AsType SomethingError e, MonadError e m) => m ()
```

In 2.2.1.0 we can write
```haskell
data AppError = AESomething SomethingError | AEOther Text
  deriving (Generic)

app :: ExceptT AppError IO ()
app = do
  ...
  doSomething
  ...
```

But
```haskell
app :: ExceptT SomethingError IO ()
app = do
  ...
  doSomething
  ...
```
gives an error like `The type SomethingError does not contain a constructor whose field is of type 
SomethingError`.

Is there a good reason why we can't add `instance AsType a a`? Or is there a different way to achieve this kind of behaviour?

_Originally posted by @lrworth in https://github.com/kcsongor/generic-lens/issues/85#issuecomment-1056024535_

### PR DESCRIPTION
**Pull request by lrworth**
Resolves #146

### CODE REVIEW

**Comment by JackKelly-Bellroy** [comment]
Is there anything we can do to help move this along?

**Comment by Tristano8** [comment]
Gentle bump - would appreciate if this could be reviewed/merged

**Review by michaelpj — APPROVED** [review]
Alright, this looks good then!

**Comment by michaelpj** [comment]
Could you fix the changelog conflict, please?

**Comment by lrworth** [comment]
I've updated the wording of `AsType` and `HasType` haddocks to permit the reflexive instances, and would like someone to proof-read what I've written.

**Review by michaelpj — APPROVED** [review]
Reads fine to me, thanks!

**Pull request merged**
