### PR TITLE
Update CI to set 8.10.7, 9.0.1 and 9.2.1 as targets.

### PR DESCRIPTION
**Pull request by danwdart**
Helps with #139

### CODE REVIEW

**Comment by danwdart** [comment]
Hmm, Ubuntu doesn't have either 9.2.1 or 8.10.7 at its disposal, and at 9.0.1 it might need a doctest jailbreak or something. Perhaps a PPA could be used to offer the missing versions.

**Comment by danwdart** [comment]
Being a library it seems kind of pointless to keep < 8.10.7 as Snoyman suggested in his blog post: https://www.snoyman.com/blog/2018/07/stop-supporting-older-ghcs/ - but on use case here I'm unsure.

**Comment by raehik** [comment]
I ran `haskell-ci regenerate` with the newest version of haskell-ci and now all jobs build, except for 9.2.1 failing on the tests. https://github.com/raehik/generic-lens/pull/1
Would it be useful if I made a 9.2.1 support PR that includes @danwdart 's #139 fixes and adds 9.0.1, 9.2.1 to CI? Then only the failing tests would remain.

**Comment by danwdart** [comment]
I believe that's what I meant  to do - to add the fixes before this ticket

**Comment by DrewFenwick** [comment]
> I ran haskell-ci regenerate with the newest version of haskell-ci and now all jobs build, except for 9.2.1 failing on the tests. raehik#1

It seems like @raehik's work is ready to go, right? Broken tests sound like a separate issue to failing CI.
What needs to be done to get it ready for merging?

**Comment by raehik** [comment]
@DrewFenwick In my head, there are three fixes pending:

  * fix building on GHC 9.2
  * fix CI (doctest issues, missing GHCs)
  * fix tests on GHC 9.2 (and 9.0?)

#139 fixes building on GHC 9.2 and is ready to merge as-is. Release should only need a minor version bump.

My PR fixes CI. It tentatively "fixes" tests too, but some of the fixes are just explicitly disabling inspection tests. That warrants some discussion still.

**Comment by kcsongor** [comment]
Thanks for all the work everyone, I'll make a release this weekend! I'll look at the inspection tests and see how far off they are. They've always been really tricky to keep up to date unfortunately, as they tend to break in very subtle ways with each GHC release.

**Comment by raehik** [comment]
Thanks a ton for your library! I'll rebase my PR off #139 and clean it up before the weekend.

**Comment by raehik** [comment]
PR good to go at #141. Could merge #139 first then rebase+merge, or maybe merge directly (it's based off #139).

**Comment by kcsongor** [comment]
Merged #141, thanks again!

**Pull request closed without merging**
