### PR TITLE
indexed profunctors

### PR DESCRIPTION
**Pull request by phadej**
I rebased `indexed-profunctors` branch and made some small things, so at least travis should be happy

TODO: 
- [ ] Data.Generics.Product.Constraints doens't make sense for `optics`, does it?
- [ ] Data.Generics.Product.HList needs wrappers in both `generic-lens` and `generic-optics`
- [ ] clean up

### CODE REVIEW

**Comment by phadej** [comment]
inspection tests are broken

---

```haskell
fieldALensManual :: Lens' Record Int
fieldALensManual = lensVL $ \f (MkRecord a b) -> (\a' -> MkRecord a' b) <$> f a
```

`linear` vs `dimap . second`

```
    LHS:
        fieldALensManual
        fieldALensManual = fieldALensManual_sj2M `cast` <Co:38>
        
        l2
        l2
          = \ @ f $dFunctor_adX1 f ds_didi ->
              case ds_didi of { MkRecord a b ->
              fmap $dFunctor_adX1 (\ a' -> MkRecord a' b) (f a)
              }
        
        fieldALensManual_sj2M
        fieldALensManual_sj2M
          = \ @ p @ i _ irred -> linear (irred `cast` <Co:3>) l2
        
    RHS:
        fieldALensName
        fieldALensName = $dHasField0_skLk `cast` <Co:38>
        
        lvl_sl6Q
        lvl_sl6Q
          = \ x ->
              case x of { MkRecord g1 g2 -> ((g2 `cast` <Co:30>, ()), g1) }
        
        lvl_sl6R
        lvl_sl6R
          = \ x ->
              case x of { (ds2, b2) ->
              case ds2 of { (c2, c3) -> MkRecord b2 (c2 `cast` <Co:28>) }
              }
        
        $dHasField0_skLk
        $dHasField0_skLk
          = \ @ p @ i _ irred2 eta_XeU ->
              dimap
                ($p1Strong (irred2 `cast` <Co:3>))
                lvl_sl6Q
                lvl_sl6R
                (second' (irred2 `cast` <Co:3>) eta_XeU)
```

---

```haskell
fieldALensManual :: Lens' Record Int
fieldALensManual = lens (\(MkRecord a _) -> a) $ \(MkRecord _ b) x -> MkRecord x b
```

`dimap . first` vs `diman . second`

```
    LHS:
        fieldALensManual
        fieldALensManual = fieldALensManual_sj8s `cast` <Co:8>
        
        lvl_slc6
        lvl_slc6 = \ s1 -> (case s1 of { MkRecord a ds_diin -> a }, s1)
        
        lvl_slc7
        lvl_slc7
          = \ ds ->
              case ds of { (b1, s1) ->
              case s1 of { MkRecord ds_diiu b -> MkRecord b1 b }
              }
        
        $wfieldALensManual
        $wfieldALensManual
          = \ @ p @ i w_sn6y ->
              let {
                f
                f = dimap ($p1Strong (w_sn6y `cast` <Co:3>)) lvl_slc6 lvl_slc7 } in
              (\ x -> f (first' (w_sn6y `cast` <Co:3>) x)) `cast` <Co:11>
        
        fieldALensManual_sj8s
        fieldALensManual_sj8s
          = \ @ p @ i _ w_sn6y -> $wfieldALensManual w_sn6y
        
    RHS:
        fieldALensName
        fieldALensName = $dHasField0_skQZ `cast` <Co:38>
        
        lvl_slcD
        lvl_slcD
          = \ x ->
              case x of { MkRecord g1 g2 -> ((g2 `cast` <Co:30>, ()), g1) }
        
        lvl_slcE
        lvl_slcE
          = \ x ->
              case x of { (ds2, b2) ->
              case ds2 of { (c2, c3) -> MkRecord b2 (c2 `cast` <Co:28>) }
              }
        
        $dHasField0_skQZ
        $dHasField0_skQZ
          = \ @ p @ i _ irred2 eta_XeS ->
              dimap
                ($p1Strong (irred2 `cast` <Co:3>))
                lvl_slcD
                lvl_slcE
                (second' (irred2 `cast` <Co:3>) eta_XeS)
```

**Comment by phadej** [comment]
prisms fail subtly

```
test/Spec.hs:252:7: subtypePrismManual === subtypePrismGeneric failed:
    LHS:
        subtypePrismManual
        subtypePrismManual = subtypePrismManual_sj97 `cast` <Co:8>
        
        $wsubtypePrismManual
        $wsubtypePrismManual
          = \ @ p @ i w_sn7q ->
              let {
                f
                f = dimap ($p1Choice (w_sn7q `cast` <Co:3>)) lvl_snGT lvl_snGU } in
              (\ x -> f (right' (w_sn7q `cast` <Co:3>) x)) `cast` <Co:11>
        
        subtypePrismManual_sj97
        subtypePrismManual_sj97
          = \ @ p @ i _ w_sn7q -> $wsubtypePrismManual w_sn7q
        
    RHS:
        subtypePrismGeneric
        subtypePrismGeneric
          = $s$fAsSubtypesubsup_$c_Sub_smfE `cast` <Co:38>
        
        $w$s$fAsSubtypesubsup_$c_Sub
        $w$s$fAsSubtypesubsup_$c_Sub
          = \ @ p @ i w_sn4t w_sn4u ->
              dimap
                ($p1Choice (w_sn4t `cast` <Co:3>))
                lvl_snGT
                lvl_snGU
                (right' (w_sn4t `cast` <Co:3>) w_sn4u)
        
        $s$fAsSubtypesubsup_$c_Sub_smfE
        $s$fAsSubtypesubsup_$c_Sub_smfE
          = \ @ p @ i _ w_sn4t w_sn4u ->
              $w$s$fAsSubtypesubsup_$c_Sub w_sn4t w_sn4u
```

---

traversals work

**Comment by phadej** [comment]
Finally. Travis is happy, but there's still work to do.

Will you @kcsongor continue from here?

**Comment by phadej** [comment]
ping @kcsongor

**Comment by kcsongor** [comment]
Yes! Sorry for not being very active, I've been quite busy with university duties recently, but I do plan on finishing this up in the next couple weeks.

**Comment by phadej** [comment]
Friendly ping

**Comment by phadej** [comment]
another ping

**Comment by kcsongor** [comment]
I'll incorporate your changes here into https://github.com/kcsongor/generic-lens/pull/104, where I decided to start this from scratch, as the indexed-profunctors branch wasn't very cleanly separated.

**Comment by phadej** [comment]
Thanks!, closing this thus.

**Pull request closed without merging**
