### PR TITLE
Add a missing fundep to HasField

### PR DESCRIPTION
**Pull request by duog**
I think this probably improves inference somewhat, but I don't have a good example.

### CODE REVIEW

**Comment by kcsongor** [comment]
Great, thanks!
This fundep definitely didn't use to pass, but it seems that reworking the type inference algorithm made this work too. I think it should be possible to add it to the positional one as well, then?

**Comment by duog** [comment]
It passes the test suite, so I guess so!

**Comment by duog** [comment]
Hold up, looks like there are problems on newer ghcs, investigating.

**Comment by kcsongor** [comment]
Interesting. I have also been experiencing a stricter coverage condition check on 8.2... It's hard to tell if it's a bug, or a bug fixed though.

**Comment by duog** [comment]
I expect that anything to do with functional dependencies getting less permissive is a bug fix, see
https://ghc.haskell.org/trac/ghc/ticket/10675

**Comment by kcsongor** [comment]
Agreed. Either way, these fundeps are definitely valid, morally anyway - I'll see if 8.2's checker can be satisfied about them.

**Comment by duog** [comment]
I am not optimistic that it can be satisfied, I think you'll need TypeFamilyDependencies on the type families in Data.Generics.Internal.Families.Changing. I've found TypeFamilyDependencies impotent whenever I've tried to use them.

**Comment by kcsongor** [comment]
The reason this didn't work was that the way `GHasPosition`'s resolution was implemented. This has been refactored on the feature/labeled-list branch, so I included these fundeps there.
Thanks again!

**Comment by kcsongor** [comment]
If you happen to spot more of these, do let me know!

**Pull request closed without merging**
